### ISSUE TITLE
Unable to watch streamers marked age restriced before watching

### ISSUE THREAD

**Issue by melon095** [revzim/ttv-viewer#1]
Basically if the stream has the mature audience before you watch it gets stuck at loading forever.
 I 
V 

![image](https://user-images.githubusercontent.com/24413121/102734149-69aedc00-433f-11eb-9597-074c16283159.png)

**Comment by revzim** [comment]
I have not seen that problem yet with 'mature' streams, but I'm sorry to hear you're running into an issue.

Without further information, the only advice I can give is to try to refresh the application with Ctrl+R or Ctrl+Shift+R or try exiting and restarting the app, then go back to the stream and see if the problem persists.

What operating system are you running the app on, windows or mac? As well as, what version of the application you installed.
By the screenshot provided, it looks like you are on the older version, but I could be wrong.

If for some reason, you installed an older version, here is a link to the newest version [0.0.21](https://github.com/revzim/ttv-viewer/releases/tag/0.0.21).
