### ISSUE TITLE
PURPLE MESSAGE SCREEN

### ISSUE THREAD

**Issue by revzim** [revzim/ttv-viewer#6]
## PURPLE MESSAGE SCREEN BUGS/DISCUSSION

![CREDIT N3ars](https://user-images.githubusercontent.com/41067116/102773730-0302e000-438a-11eb-9b26-d50b282bd308.png)
##### purple screen appears instead of ads*
* pre-roll:
  * before stream begins
  * navigating between one streamer->another
  * resetting player via ffz 'reset player' button.
* mid-roll:
  * during stream/broadcast at random* intervals

**Comment by RoyRiv3r** [comment]
Alternate Player for Twitch.tv got an update yesterday and there are no ads or purple screen for me, i really don't like this addon since i got a big delay and buffers on the stream. I decided to check what he did on his addon since previous update and seems like he modified something about ads, can't really tell what he did tho, it's also in full russian lol, but i don't know if this works as same way as yours, another thing to investigate?
![mffz1zl](https://user-images.githubusercontent.com/41067116/103043104-078eea80-457c-11eb-865c-2bc39feee453.png)

**Comment by revzim** [comment]
After a quick glance, it looks like the author figured out the correct pre-flight request to intercept as well as how to correctly spoof a correct token to skip ads/pre-roll/purple message screens(?)*.

The good news is, I already have a method like this in my app that intercepts these exact 'recordadevent' operations that I was using to debug and hopefully figure out what it looks like this author figured out.  It also looks like he modifies the query params of some requests, which may or may not have any effect. However, due to the language barrier, it will take some time to decipher and fully understand it.

Due to the inconsistency of these purple messages, I've become more skeptical and have wanted to test streams for longer periods of time.  If/when I find something consistent, I'll post an update here and thanks for bringing this to my attention.

Edit: I didn't feel like looking through and trying to decipher more of that code; however, I ended up doing some more debugging/testing and believe I've found out how to circumvent the purple screen message (hopefully). Install the new build whenever you get a chance and let me know how it goes after watching for a little while.

## [0.0.23a](https://github.com/revzim/ttv-viewer/releases/tag/0.0.23a)

**Comment by RoyRiv3r** [comment]
I'll try this new version and post here if anything change.
@revzim Thank you for putting a bit of your time and for your effort.

**Comment by RoyRiv3r** [comment]
I just did get a purple screen watching Dafran in the new version 0.0.23a. 
![RJgvH6x](https://user-images.githubusercontent.com/41067116/103090375-254a6700-45f1-11eb-8534-dc57d62b5dbb.png)

Just noticed when i start a stream something is blocking ad at the beginning in the Alternative Twitch addon, maybe this could help 
![0eqfozU](https://user-images.githubusercontent.com/41067116/103091202-b6224200-45f3-11eb-8cce-d7f2a2dada84.png)

Also all good @revzim you don't have to spend all your free time to trying to fix the ads, you really did more than what i expected, i can stick with what twitch5 did, sorry for disturbing 👍

**Comment by revzim** [comment]
There's no reason to apologize, don't worry, you're not disturbing me and thank you for the kind words.  But, yeah as of right now, I'm a little burnt out trying to solve this due to all of the inconsistencies to be honest, but I will try to monitor other threads and update if I find anything new.

Thank you for testing my application for the time being, appreciate it. Have a happy holidays.

**Comment by RoyRiv3r** [comment]
Happy holidays to you too my friend !

Some people are saying that this script is working, i'm trying it out right now https://greasyfork.org/en/scripts/419015-twitch-ad-blocker/code

EDIT : nope doesn't work

**Comment by revzim** [comment]
I added a bypass to the purple screen. It's pretty hacky, but it does the job well enough for me. Closing until it breaks/is patched.
